[package]
name = "mail"
version = "0.10.1"
authors = ["Enrique Buendia L"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre="0.9.5"
lettre_email = "0.9.4"
mime="0.3.16"


